/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.util.List;
import javax.swing.JOptionPane;
import models.ModeloTabela;
import models.Produto;
import models.ProdutoDAO;

/**
 *
 * @author aadel
 */
public class Editar extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    ProdutoDAO pDAO = new ProdutoDAO();
    ModeloTabela modeloTabela = new ModeloTabela();
    List<Produto> lista;
    Produto produto = new Produto();

    public Editar() {
        initComponents();
        pnlAtualizar.setVisible(false);
        this.setLocationRelativeTo(null);
        tabelaMercado.setModel(modeloTabela);
        listarProdutos();

    }

    public void listarProdutos() {
        modeloTabela.atualizar();
        lista = pDAO.listar();
        modeloTabela.adicionarLinha(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAtualizar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblAtualizar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlCadastrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlLoja = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMercado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1010, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAtualizar.setBackground(new java.awt.Color(22, 33, 53));
        pnlAtualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Codigo");
        pnlAtualizar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        pnlAtualizar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 10));

        txtCodigo.setBackground(new java.awt.Color(22, 33, 53));
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(240, 240, 240));
        txtCodigo.setBorder(null);
        pnlAtualizar.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 57, 190, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Nome");
        pnlAtualizar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        txtNome.setBackground(new java.awt.Color(22, 33, 53));
        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(240, 240, 240));
        txtNome.setBorder(null);
        pnlAtualizar.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 190, 30));
        pnlAtualizar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, 10));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Preço");
        pnlAtualizar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtPreco.setBackground(new java.awt.Color(22, 33, 53));
        txtPreco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPreco.setForeground(new java.awt.Color(240, 240, 240));
        txtPreco.setBorder(null);
        pnlAtualizar.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 30));
        pnlAtualizar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 10));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Quantidade");
        pnlAtualizar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        txtQtd.setBackground(new java.awt.Color(22, 33, 53));
        txtQtd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQtd.setForeground(new java.awt.Color(240, 240, 240));
        txtQtd.setBorder(null);
        pnlAtualizar.add(txtQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 190, 30));
        pnlAtualizar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 10));

        lblAtualizar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAtualizar.setForeground(new java.awt.Color(240, 240, 240));
        lblAtualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtualizar.setText("Atualizar");
        lblAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtualizarMouseClicked(evt);
            }
        });
        pnlAtualizar.add(lblAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 392, 170, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/button (1).png"))); // NOI18N
        pnlAtualizar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 320, 350, 130));

        lblCancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(240, 240, 240));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("Cancelar");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        pnlAtualizar.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 170, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/button (1).png"))); // NOI18N
        pnlAtualizar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 350, 130));

        getContentPane().add(pnlAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 640, 460));

        jPanel1.setBackground(new java.awt.Color(22, 33, 53));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCadastrar.setBackground(new java.awt.Color(22, 33, 53));
        pnlCadastrar.setPreferredSize(new java.awt.Dimension(220, 80));
        pnlCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCadastrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N

        javax.swing.GroupLayout pnlCadastrarLayout = new javax.swing.GroupLayout(pnlCadastrar);
        pnlCadastrar.setLayout(pnlCadastrarLayout);
        pnlCadastrarLayout.setHorizontalGroup(
            pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );
        pnlCadastrarLayout.setVerticalGroup(
            pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21))
        );

        jPanel1.add(pnlCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlLoja.setBackground(new java.awt.Color(22, 33, 53));
        pnlLoja.setPreferredSize(new java.awt.Dimension(220, 80));
        pnlLoja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLojaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Loja");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/shoppaymentorderbuy-20_icon-icons.com_73877.png"))); // NOI18N

        javax.swing.GroupLayout pnlLojaLayout = new javax.swing.GroupLayout(pnlLoja);
        pnlLoja.setLayout(pnlLojaLayout);
        pnlLojaLayout.setHorizontalGroup(
            pnlLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlLojaLayout.setVerticalGroup(
            pnlLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLojaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20))
        );

        jPanel1.add(pnlLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jPanel4.setBackground(new java.awt.Color(39, 55, 80));
        jPanel4.setPreferredSize(new java.awt.Dimension(220, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Editar");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/draw_line_icon-icons.com_51076 (1).png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 63, 68));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tabelaMercado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "PREÇO", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMercadoMouseClicked(evt);
            }
        });
        tabelaMercado.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tabelaMercadoInputMethodTextChanged(evt);
            }
        });
        tabelaMercado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabelaMercadoPropertyChange(evt);
            }
        });
        tabelaMercado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaMercadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMercado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 800, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMercadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabelaMercadoPropertyChange

    }//GEN-LAST:event_tabelaMercadoPropertyChange

    private void tabelaMercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMercadoMouseClicked

    }//GEN-LAST:event_tabelaMercadoMouseClicked

    private void tabelaMercadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaMercadoKeyPressed
        //Verificando se foi pressionado a tecla delete
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {
            //Verificando se tem uma linha para apagar
            if (tabelaMercado.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para apagar");
            } else {
                //Pegando o codigo da linha selecionada
                Object obj = tabelaMercado.getValueAt(tabelaMercado.getSelectedRow(), 0);
                int conf = JOptionPane.showConfirmDialog(null, "Deseja apagar este produto?");
                if (conf == 0) {
                    boolean resultado = pDAO.deletar(obj.toString());
                    if (resultado == true) {
                        modeloTabela.atualizar();
                        lista = pDAO.listar();
                        modeloTabela.adicionarLinha(lista);
                    }
                }
            }
        }

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_A) {
            pnlAtualizar.setVisible(true);

            if (tabelaMercado.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para apagar");
            } else {
                //Pegando o codigo da linha selecionada
                Object obj = tabelaMercado.getValueAt(tabelaMercado.getSelectedRow(), 0);
                produto = pDAO.buscarProduto(obj.toString());
                txtCodigo.setText(produto.getCodigo());
                txtNome.setText(produto.getNome());
                txtPreco.setText(String.valueOf(produto.getPreco()));
                txtQtd.setText(String.valueOf(produto.getQtd()));
            }

        }
    }//GEN-LAST:event_tabelaMercadoKeyPressed

    private void pnlLojaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLojaMouseClicked
        this.setVisible(false);
        new Loja().setVisible(true);

    }//GEN-LAST:event_pnlLojaMouseClicked

    private void pnlCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCadastrarMouseClicked
        this.setVisible(false);
        new InserirProduto().setVisible(true);
    }//GEN-LAST:event_pnlCadastrarMouseClicked

    private void tabelaMercadoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tabelaMercadoInputMethodTextChanged

    }//GEN-LAST:event_tabelaMercadoInputMethodTextChanged

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        pnlAtualizar.setVisible(false);
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void lblAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtualizarMouseClicked
        produto.setNome(txtNome.getText());
        produto.setPreco(Float.parseFloat(txtPreco.getText()));
        produto.setCodigo(txtCodigo.getText());
        produto.setQtd(Integer.parseInt(txtCodigo.getText()));
        boolean resu = pDAO.atualiza(produto);
        if (resu == true) {
            pnlAtualizar.setVisible(false);
            modeloTabela.atualizar();
            lista = pDAO.listar();
            modeloTabela.adicionarLinha(lista);
        }

    }//GEN-LAST:event_lblAtualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAtualizar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JPanel pnlAtualizar;
    private javax.swing.JPanel pnlCadastrar;
    private javax.swing.JPanel pnlLoja;
    private javax.swing.JTable tabelaMercado;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
