/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.util.List;
import javax.swing.JOptionPane;
import models.ModeloTabela;
import models.Produto;
import models.ProdutoDAO;

/**
 *
 * @author aadel
 */
public class Editar extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    ProdutoDAO pDAO = new ProdutoDAO();
    ModeloTabela modeloTabela = new ModeloTabela();
    List<Produto> lista;

    public Editar() {
        initComponents();
        this.setLocationRelativeTo(null);
        tabelaMercado.setModel(modeloTabela);
        listarProdutos();

    }

    public void listarProdutos() {
        modeloTabela.atualizar();
        lista = pDAO.listar();
        modeloTabela.adicionarLinha(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMercado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1010, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 33, 53));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 710));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tabelaMercado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "PREÇO", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMercadoMouseClicked(evt);
            }
        });
        tabelaMercado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabelaMercadoPropertyChange(evt);
            }
        });
        tabelaMercado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaMercadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMercado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 800, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMercadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabelaMercadoPropertyChange

    }//GEN-LAST:event_tabelaMercadoPropertyChange

    private void tabelaMercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMercadoMouseClicked


    }//GEN-LAST:event_tabelaMercadoMouseClicked

    private void tabelaMercadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaMercadoKeyPressed
        //Verificando se foi pressionado a tecla delete
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {
            //Verificando se tem uma linha para apagar
            if (tabelaMercado.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma linha para apagar");
            } else {
                //Pegando o codigo da linha selecionada
                Object obj = tabelaMercado.getValueAt(tabelaMercado.getSelectedRow(), 0);
                int conf = JOptionPane.showConfirmDialog(null, "Deseja apagar este produto?");
                if (conf == 0) {
                    boolean resultado = pDAO.deletar(obj.toString());
                    if (resultado == true) {
                        modeloTabela.atualizar();
                        lista = pDAO.listar();
                        modeloTabela.adicionarLinha(lista);
                    }
                }
            }
        }
    }//GEN-LAST:event_tabelaMercadoKeyPressed

    public void apagarDado() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaMercado;
    // End of variables declaration//GEN-END:variables
}
