/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ModeloTabela;
import models.Produto;
import models.ProdutoDAO;

/**
 *
 * @author aadel
 */
public class Loja extends javax.swing.JFrame {
    //Variável Global para fazer o resultado da compra

    float totalCompra;
    //Array para pegar cada id para depois ser excluido do banco
    List<String> listaId = new ArrayList<>();
    //Array para pegar cada quantidade para depois ser excluido do banco
    List<Integer> listaQtd = new ArrayList<>();

    /**
     * Creates new form Loja
     */
    public Loja() {
        initComponents();
        this.setLocationRelativeTo(null);
        modalDados.setVisible(false);
        pnlFinalizarCompra.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFinalizarCompra = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTotalCompra = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtPagamento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        modalDados = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        txtQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblCancelarProduto = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMercado = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtResultadoCompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pnlPesquisar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlCadastrar1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlLoja1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFinalizarCompra.setBackground(new java.awt.Color(22, 33, 53));
        pnlFinalizarCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Pagamento");
        pnlFinalizarCompra.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        txtTotalCompra.setBackground(new java.awt.Color(22, 33, 53));
        txtTotalCompra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTotalCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCompra.setBorder(null);
        pnlFinalizarCompra.add(txtTotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 30));
        pnlFinalizarCompra.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 50));
        pnlFinalizarCompra.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, -1));

        txtPagamento.setBackground(new java.awt.Color(22, 33, 53));
        txtPagamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPagamento.setForeground(new java.awt.Color(255, 255, 255));
        txtPagamento.setBorder(null);
        txtPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPagamentoKeyPressed(evt);
            }
        });
        pnlFinalizarCompra.add(txtPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Total");
        pnlFinalizarCompra.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Troco");
        pnlFinalizarCompra.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 30));

        txtTroco.setBackground(new java.awt.Color(22, 33, 53));
        txtTroco.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTroco.setForeground(new java.awt.Color(255, 255, 255));
        txtTroco.setBorder(null);
        txtTroco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTrocoKeyPressed(evt);
            }
        });
        pnlFinalizarCompra.add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 40));
        pnlFinalizarCompra.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("R$");
        pnlFinalizarCompra.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        getContentPane().add(pnlFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 430, 310));

        modalDados.setBackground(new java.awt.Color(22, 33, 53));
        modalDados.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray));
        modalDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        modalDados.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 224, 10));

        txtQtd.setBackground(new java.awt.Color(22, 33, 53));
        txtQtd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtQtd.setForeground(new java.awt.Color(255, 255, 255));
        txtQtd.setBorder(null);
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
        });
        modalDados.add(txtQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 224, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Quantidade");
        modalDados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        lblCancelarProduto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCancelarProduto.setForeground(new java.awt.Color(240, 240, 240));
        lblCancelarProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelarProduto.setText("Cancelar");
        lblCancelarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblCancelarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarProdutoMouseClicked(evt);
            }
        });
        modalDados.add(lblCancelarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 170, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/button (1).png"))); // NOI18N
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        modalDados.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 360, 130));

        getContentPane().add(modalDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 460, 380));

        jPanel3.setBackground(new java.awt.Color(21, 28, 52));

        jSeparator1.setForeground(new java.awt.Color(240, 240, 240));

        txtProduto.setBackground(new java.awt.Color(21, 28, 52));
        txtProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProduto.setForeground(new java.awt.Color(240, 240, 240));
        txtProduto.setBorder(null);
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdutoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(txtProduto))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 790, 100));

        tabelaMercado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOME", "PREÇO", "QUANTIDADE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaMercado);
        if (tabelaMercado.getColumnModel().getColumnCount() > 0) {
            tabelaMercado.getColumnModel().getColumn(0).setResizable(false);
            tabelaMercado.getColumnModel().getColumn(1).setResizable(false);
            tabelaMercado.getColumnModel().getColumn(2).setResizable(false);
            tabelaMercado.getColumnModel().getColumn(3).setResizable(false);
            tabelaMercado.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 780, 490));

        jPanel5.setBackground(new java.awt.Color(21, 28, 52));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 10, 490));

        jPanel4.setBackground(new java.awt.Color(21, 28, 52));
        jPanel4.setEnabled(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/shoppaymentorderbuy-04_icon-icons.com_73886.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("R$");

        txtResultadoCompra.setEditable(false);
        txtResultadoCompra.setBackground(new java.awt.Color(21, 28, 52));
        txtResultadoCompra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtResultadoCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtResultadoCompra.setBorder(null);

        jLabel8.setBackground(new java.awt.Color(39, 55, 80));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("F4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(450, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txtResultadoCompra))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtResultadoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 790, 120));

        jPanel6.setBackground(new java.awt.Color(22, 33, 53));
        jPanel6.setPreferredSize(new java.awt.Dimension(220, 710));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPesquisar.setBackground(new java.awt.Color(22, 33, 53));
        pnlPesquisar.setPreferredSize(new java.awt.Dimension(220, 80));
        pnlPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPesquisarMouseClicked(evt);
            }
        });
        pnlPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Pesquisar");
        pnlPesquisar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/3-search-cat_icon-icons.com_76679.png"))); // NOI18N
        pnlPesquisar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 80, 68));

        jPanel6.add(pnlPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        pnlCadastrar1.setBackground(new java.awt.Color(22, 33, 53));
        pnlCadastrar1.setPreferredSize(new java.awt.Dimension(220, 80));
        pnlCadastrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCadastrar1MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cadastrar");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N

        javax.swing.GroupLayout pnlCadastrar1Layout = new javax.swing.GroupLayout(pnlCadastrar1);
        pnlCadastrar1.setLayout(pnlCadastrar1Layout);
        pnlCadastrar1Layout.setHorizontalGroup(
            pnlCadastrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(21, 21, 21))
        );
        pnlCadastrar1Layout.setVerticalGroup(
            pnlCadastrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadastrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(21, 21, 21))
        );

        jPanel6.add(pnlCadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlLoja1.setBackground(new java.awt.Color(39, 55, 80));
        pnlLoja1.setPreferredSize(new java.awt.Dimension(220, 80));
        pnlLoja1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLoja1MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Loja");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/shoppaymentorderbuy-20_icon-icons.com_73877.png"))); // NOI18N

        javax.swing.GroupLayout pnlLoja1Layout = new javax.swing.GroupLayout(pnlLoja1);
        pnlLoja1.setLayout(pnlLoja1Layout);
        pnlLoja1Layout.setHorizontalGroup(
            pnlLoja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoja1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(36, 36, 36)
                .addComponent(jLabel18)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        pnlLoja1Layout.setVerticalGroup(
            pnlLoja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoja1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlLoja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(20, 20, 20))
        );

        jPanel6.add(pnlLoja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jPanel7.setBackground(new java.awt.Color(22, 33, 53));
        jPanel7.setPreferredSize(new java.awt.Dimension(220, 80));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Editar");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 60));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/Imagens/draw_line_icon-icons.com_51076 (1).png"))); // NOI18N
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 63, 68));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if ("".equals(txtProduto.getText().trim()) || " ".equals(txtProduto.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Digite um código válido");
            } else {
                modalDados.setVisible(true);
                txtQtd.requestFocusInWindow();
            }
        }

        if (key == KeyEvent.VK_F4) {
            pnlFinalizarCompra.setVisible(true);
            txtTotalCompra.setText(String.valueOf(totalCompra));
            txtPagamento.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtProdutoKeyPressed

    private void lblCancelarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarProdutoMouseClicked
        txtQtd.setText("");
        txtProduto.setText("");
        modalDados.setVisible(false);
    }//GEN-LAST:event_lblCancelarProdutoMouseClicked

    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if ("".equals(txtQtd.getText().trim()) || " ".equals(txtQtd.getText().trim())) {
                insertTabela(1);
                modalDados.setVisible(false);
            } else {
                int qtd = Integer.parseInt(txtQtd.getText());
                insertTabela(qtd);
                modalDados.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtQtdKeyPressed


    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void txtPagamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagamentoKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            txtTroco.setText(String.valueOf(Float.parseFloat(txtPagamento.getText()) - totalCompra));
            int conf = JOptionPane.showConfirmDialog(null, "Limpar compra?");
            if (conf == 0) {
                ProdutoDAO dao = new ProdutoDAO();
                //Retirando do estoque
                for (int i = 0; i < listaId.size(); i++) {
                    dao.retiraEstoque(listaId.get(i), listaQtd.get(i));
                }
                //Limpando a mémoria;
                listaId = null;
                listaQtd = null;
                txtResultadoCompra.setText("");
                //Limpando a tabela
                while (tabelaMercado.getModel().getRowCount() > 0) {
                    ((DefaultTableModel) tabelaMercado.getModel()).removeRow(0);
                }
                
                pnlFinalizarCompra.setVisible(false);
            }
        }


    }//GEN-LAST:event_txtPagamentoKeyPressed

    private void txtTrocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrocoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrocoKeyPressed

    private void pnlPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPesquisarMouseClicked
        this.setVisible(false);
        new Pesquisar().setVisible(true);
    }//GEN-LAST:event_pnlPesquisarMouseClicked

    private void pnlCadastrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCadastrar1MouseClicked
        this.setVisible(false);
        new InserirProduto().setVisible(true);
    }//GEN-LAST:event_pnlCadastrar1MouseClicked

    private void pnlLoja1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLoja1MouseClicked
        this.setVisible(false);
        new Loja().setVisible(true);
    }//GEN-LAST:event_pnlLoja1MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        this.setVisible(false);
        new Editar().setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    public void insertTabela(int qtd) {

        String codigo = txtProduto.getText().trim();
        Produto produto = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        //Buscando produto
        produto = dao.buscarProduto(codigo);
        //salvando em String os dados para poder passar a tabela

        String nomeProduto = produto.getNome();
        String precoProduto = String.valueOf(produto.getPreco());
        String qtdProduto = String.valueOf(qtd);
        String totalProduto = String.valueOf(qtd * produto.getPreco());
        listaId.add(codigo);
        listaQtd.add(qtd);
        //Verificando se chegou vazio
        if ("0.0".equals(precoProduto)) {
            JOptionPane.showMessageDialog(null, "Não cadastrado");
        } else {
            //Criando o modelo de tabela
            DefaultTableModel val = (DefaultTableModel) tabelaMercado.getModel();
            //Adicionando as linhas
            val.addRow(new String[]{codigo, nomeProduto, precoProduto, qtdProduto, totalProduto});
            //Limpando os campos
            txtProduto.setText("");
            txtQtd.setText("");
            //Pegando o total da compra
            totalCompra = totalCompra + qtd * produto.getPreco();
            
            txtResultadoCompra.setText(String.valueOf(totalCompra));
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblCancelarProduto;
    private javax.swing.JPanel modalDados;
    private javax.swing.JPanel pnlCadastrar1;
    private javax.swing.JPanel pnlFinalizarCompra;
    private javax.swing.JPanel pnlLoja1;
    private javax.swing.JPanel pnlPesquisar;
    private javax.swing.JTable tabelaMercado;
    private javax.swing.JTextField txtPagamento;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtResultadoCompra;
    private javax.swing.JTextField txtTotalCompra;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
